version: "3.9"

services:
  postgres:
    container_name: postgres_dps
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dps
      - POSTGRES_PASSWORD=dps001
      - POSTGRES_DB=dps
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./dps-api/db/tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
